-- ============================================================
-- Fantasy Soccer League Database
-- File: import_users.sql
-- Method 3: CSV File Import — loading USERS from users.csv
--
-- The file users.csv was generated by generate_data.py and
-- contains 500 user records with columns:
--   user_id, username, email, password_hash, country,
--   registration_date, birth_date
--
-- This file demonstrates how the same data can be loaded
-- via the database CSV import facility rather than INSERT.
-- ============================================================

-- PostgreSQL: use the COPY command to import CSV
-- (adjust path to the absolute location of users.csv on your system)

COPY USERS (user_id, username, email, password_hash, country, registration_date, birth_date)
FROM '/absolute/path/to/DataImportFiles/users.csv'
WITH (
    FORMAT CSV,
    HEADER TRUE,
    DELIMITER ','
);

-- Alternative: psql command-line (run from terminal, not inside SQL session):
-- \COPY USERS (user_id, username, email, password_hash, country, registration_date, birth_date)
-- FROM 'DataImportFiles/users.csv'
-- WITH (FORMAT CSV, HEADER TRUE, DELIMITER ',');

-- Verify the import:
SELECT COUNT(*) AS users_imported FROM USERS;
SELECT * FROM USERS LIMIT 10;
